name: build and test
on:
  push:
  schedule:
    - cron: '0 3 * * *'
  pull_request:
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v15
      - run: nix build
  pip:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9, 3.10 ]
    steps:
      - name: install fonts
        run: sudo apt-get install fonts-noto-color-emoji
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install
        run: |
          pip install --upgrade pip
          pip3 install pytest
          pip3 install -e .
      - name: test
        run: ./test.sh
      - name: test 2
        run:  TEMCI_TEST_CMD=1 ./test.sh
